name: collections

services:
  php-apache:
    image: alonzoturner/lamp-stack:latest
    ports:
      - 80:80
    environment:
      VIRTUAL_DIR: html
      VIRTUAL_HOST: collections.subtext
      VIRTUAL_ADMIN: alonzo.turner@subtext.productions
      APP_CONFIG: unit.php
    volumes:
      - ./:/var/www
